# Generated by Django 5.1.1 on 2024-09-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('room_type', models.CharField(choices=[('S', 'Single'), ('D', 'Double'), ('T', 'Triple')], max_length=1)),
                ('price_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_avaiable', models.BooleanField(default=True)),
            ],
        ),
    ]
